export const productos = [
  // NOTEBOOKS
  {
    id: 1,
    nombre: "Notebook Lenovo IdeaPad 3",
    precio: 850000,
    stock: 12,
    categoria_id: 1,
    activo: true,
  },
  {
    id: 2,
    nombre: "Notebook HP Pavilion 15",
    precio: 1250000,
    stock: 7,
    categoria_id: 1,
    activo: true,
  },
  {
    id: 3,
    nombre: "Notebook ASUS TUF Gaming F15",
    precio: 1890000,
    stock: 5,
    categoria_id: 1,
    activo: true,
  },
  {
    id: 4,
    nombre: "Notebook Dell Inspiron 14",
    precio: 980000,
    stock: 9,
    categoria_id: 1,
    activo: true,
  },

  // PLACAS DE VIDEO
  {
    id: 5,
    nombre: "NVIDIA RTX 4060 8GB",
    precio: 780000,
    stock: 6,
    categoria_id: 2,
    activo: true,
  },
  {
    id: 6,
    nombre: "AMD Radeon RX 7600",
    precio: 690000,
    stock: 4,
    categoria_id: 2,
    activo: true,
  },
  {
    id: 7,
    nombre: "NVIDIA RTX 4070 Super",
    precio: 1250000,
    stock: 3,
    categoria_id: 2,
    activo: true,
  },
  {
    id: 8,
    nombre: "AMD Radeon RX 7900 XT",
    precio: 1650000,
    stock: 2,
    categoria_id: 2,
    activo: true,
  },

  // PROCESADORES
  {
    id: 9,
    nombre: "Intel Core i5 14600K",
    precio: 420000,
    stock: 10,
    categoria_id: 3,
    activo: true,
  },
  {
    id: 10,
    nombre: "AMD Ryzen 5 7600",
    precio: 390000,
    stock: 11,
    categoria_id: 3,
    activo: true,
  },
  {
    id: 11,
    nombre: "Intel Core i7 14700K",
    precio: 650000,
    stock: 5,
    categoria_id: 3,
    activo: true,
  },
  {
    id: 12,
    nombre: "AMD Ryzen 7 7800X3D",
    precio: 720000,
    stock: 4,
    categoria_id: 3,
    activo: true,
  },

  // MEMORIAS RAM
  {
    id: 13,
    nombre: "Kingston Fury 16GB DDR4",
    precio: 85000,
    stock: 20,
    categoria_id: 4,
    activo: true,
  },
  {
    id: 14,
    nombre: "Corsair Vengeance 32GB DDR5",
    precio: 210000,
    stock: 8,
    categoria_id: 4,
    activo: true,
  },
  {
    id: 15,
    nombre: "ADATA XPG 16GB DDR5",
    precio: 98000,
    stock: 14,
    categoria_id: 4,
    activo: true,
  },
  {
    id: 16,
    nombre: "Crucial Basics 8GB DDR4",
    precio: 42000,
    stock: 25,
    categoria_id: 4,
    activo: true,
  },

  // DISCOS SSD
  {
    id: 17,
    nombre: "Samsung 980 Pro 1TB",
    precio: 165000,
    stock: 9,
    categoria_id: 5,
    activo: true,
  },
  {
    id: 18,
    nombre: "WD Black SN850X 2TB",
    precio: 295000,
    stock: 4,
    categoria_id: 5,
    activo: true,
  },
  {
    id: 19,
    nombre: "Kingston NV2 500GB",
    precio: 58000,
    stock: 18,
    categoria_id: 5,
    activo: true,
  },
  {
    id: 20,
    nombre: "Crucial BX500 1TB",
    precio: 92000,
    stock: 13,
    categoria_id: 5,
    activo: true,
  },

  // MONITORES
  {
    id: 21,
    nombre: "Monitor LG UltraGear 24”",
    precio: 310000,
    stock: 7,
    categoria_id: 6,
    activo: false,
  },
  {
    id: 22,
    nombre: "Samsung Odyssey G5 27”",
    precio: 520000,
    stock: 5,
    categoria_id: 6,
    activo: false,
  },
  {
    id: 23,
    nombre: "ASUS ProArt Display 27”",
    precio: 680000,
    stock: 2,
    categoria_id: 6,
    activo: false,
  },
  {
    id: 24,
    nombre: "ViewSonic VX2418",
    precio: 275000,
    stock: 10,
    categoria_id: 6,
    activo: false,
  },

  // PERIFÉRICOS
  {
    id: 25,
    nombre: "Mouse Logitech G502",
    precio: 95000,
    stock: 15,
    categoria_id: 7,
    activo: true,
  },
  {
    id: 26,
    nombre: "Teclado Redragon Kumara",
    precio: 78000,
    stock: 17,
    categoria_id: 7,
    activo: true,
  },
  {
    id: 27,
    nombre: "Auriculares HyperX Cloud II",
    precio: 145000,
    stock: 6,
    categoria_id: 7,
    activo: true,
  },
  {
    id: 28,
    nombre: "Webcam Logitech C920",
    precio: 110000,
    stock: 8,
    categoria_id: 7,
    activo: true,
  },

  // FUENTES DE PODER
  {
    id: 29,
    nombre: "Corsair RM750x 750W",
    precio: 185000,
    stock: 7,
    categoria_id: 8,
    activo: true,
  },
  {
    id: 30,
    nombre: "Cooler Master 650W Bronze",
    precio: 118000,
    stock: 12,
    categoria_id: 8,
    activo: true,
  },
  {
    id: 31,
    nombre: "EVGA 600W White",
    precio: 89000,
    stock: 10,
    categoria_id: 8,
    activo: true,
  },
  {
    id: 32,
    nombre: "Gigabyte UD850GM",
    precio: 210000,
    stock: 4,
    categoria_id: 8,
    activo: true,
  },

  // MOTHERBOARDS
  {
    id: 33,
    nombre: "ASUS ROG STRIX B650",
    precio: 340000,
    stock: 5,
    categoria_id: 9,
    activo: false,
  },
  {
    id: 34,
    nombre: "MSI MAG B760 Tomahawk",
    precio: 295000,
    stock: 6,
    categoria_id: 9,
    activo: false,
  },
  {
    id: 35,
    nombre: "Gigabyte A520M",
    precio: 125000,
    stock: 9,
    categoria_id: 9,
    activo: false,
  },
  {
    id: 36,
    nombre: "ASRock X670E Steel Legend",
    precio: 510000,
    stock: 2,
    categoria_id: 9,
    activo: false,
  },

  // GABINETES
  {
    id: 37,
    nombre: "NZXT H5 Flow",
    precio: 175000,
    stock: 6,
    categoria_id: 10,
    activo: true,
  },
  {
    id: 38,
    nombre: "Corsair 4000D Airflow",
    precio: 198000,
    stock: 5,
    categoria_id: 10,
    activo: true,
  },
  {
    id: 39,
    nombre: "Redragon Wheeljack",
    precio: 98000,
    stock: 11,
    categoria_id: 10,
    activo: true,
  },
  {
    id: 40,
    nombre: "Cooler Master TD500 Mesh",
    precio: 225000,
    stock: 4,
    categoria_id: 10,
    activo: true,
  },
];
