"""agregar autor a productos

Revision ID: 2b3d7fe79fec
Revises: cc2148f40e1c
Create Date: 2026-08-08 11:39:22.306105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3d7fe79fec'
down_revision = 'cc2148f40e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.String(length=150), nullable=False))
        batch_op.alter_column('stock_actual',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('rol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('rol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('stock_minimo',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('stock_actual',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('autor')

    # ### end Alembic commands ###
